### ISSUE TITLE
Gulp load Plugins

### ISSUE THREAD

**Issue by raisiqueira** [ahmadawais/WPGulp#1]
why not use the gulp-load-plugins?

**Comment by ahmadawais** [comment]
@raisiqueira Because I like to keep in control of the variable names. Instead of predicting them, It's easier to do declare the variables on your own. It also makes simple debugging easier.

**Comment by ahmadawais** [comment]
@raisiqueira You should check https://github.com/ahmadawais/advanced-gulp-wordpress

Current repo is a Work In Progress!
