### ISSUE TITLE
In Chrome, sass source files disappear on refresh

### ISSUE THREAD

**Issue by johnvincentlovell** [ahmadawais/WPGulp#100]
In Chrome, whenever I refresh a page or if BrowserSync refreshes the page, the sass source files disappear and suddenly I'm unable to edit the style via the DevTools inspection editor. If I refresh DevTools with option+R (probably alt+R on PC), then they're back and working fine. Any idea why this might be happening or what I can do to fix this? 

This doesn't seem to be happening with Firefox and I'm working locally.

Thank you!

**Comment by ahmadawais** [comment]
Doesn't happen to me. What version are you using. Can you make a GIF?

**Comment by johnvincentlovell** [comment]
Huh. it stopped happening! i'll close it out for now. thanks!
