### ISSUE TITLE
Slow Reload Time alongside Local by Flywheel

### ISSUE THREAD

**Issue by lukereech** [ahmadawais/WPGulp#102]
As reported here - https://github.com/ahmadawais/WPGulpTheme/issues/9#issuecomment-387663545

I'm still experiencing problems, having used different WordPress builds and clones of this repo. Have had to remove the BrowserSync task from the gulpfile for now because it is slowing me down.

**Comment by ahmadawais** [comment]
You didn't answer my question here:

BTW Checkout the v2.0.0 branch of upcoming WPGulp which has a separate config file and updated modern JavaScript based workflow. Might fix the issue.

**Comment by lukereech** [comment]
Ah my apologies I missed that, will give it a try.

FYI using it, when doing an `npm install` it got stuck when trying to install the dependency 'eslint-config-wordpress@2.0.0'. I've removed it from the package.json to try get everything else installed but also getting stuck at `⸨    ░░░░░░░░░░░░░░⸩ ⠴ fetchMetadata: sill pacote range manifest for jsonify@~0.0.0 fetched in 59m` now.

**Comment by ahmadawais** [comment]
Same issue with folks here. https://github.com/BrowserSync/browser-sync/issues/1346

I solved it by enabling IPV6 as mentioned there.
