### ISSUE TITLE
Gulp consuming over 80% when running gulp with WPGulp

### ISSUE THREAD

**Issue by AviKlein** [ahmadawais/WPGulp#105]
### Expected Behavior

Normal amount of CPU usage

### Actual Behavior

I have used Gulp with other setups several times before and everything worked fine. However, when using WPGulp it's consuming a huge amount of CPU.
![image](https://user-images.githubusercontent.com/42144272/43718369-1d209002-9993-11e8-9b55-d8a0dbd91b99.png)
I tried disabling the browser sync, thinking that that might be too heavy but it didn't reduce the CPU usage.

### Steps to Reproduce

My setup is as follows:
Localhost on XAMPP
Downloaded Wordpress from the repository
Downloaded WPGulp using Curl
Node version: 10.8.0
Gulp version 3.9.1
Opened CMD in the project folder in htdocs.

I think that's it...

I'd appreciate any help I can get.

Thanks

1. `node -v`: 10.8.0
2. `npm -v`: 6.2.0

Operating system: Windows 10

**Comment by AviKlein** [comment]
I accidentally installed everything in the WP root, all is good now.
You can cancel this issue.

**Comment by ahmadawais** [comment]
@AviKlein glad you figured it out. Make sure to try out the new beta in branch `v2.0.0` it's ready just needs documentation. Also, if memory is ever an issue stop the PHP file watching it saves a bunch of it.

Peace! ✌️
