### ISSUE TITLE
Update NPM dependencies

### ISSUE THREAD

**Issue by marcoaring** [ahmadawais/WPGulp#107]
Update NPM dependencies to latest version. I've change my package.json to the following code:

"devDependencies": {
    "browser-sync": "^2.24.6",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-filter": "^5.1.0",
    "gulp-imagemin": "^4.1.0",
    "gulp-line-ending-corrector": "^1.0.2",
    "gulp-merge-media-queries": "^0.2.1",
    "gulp-notify": "^3.2.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^4.0.1",
    "gulp-sourcemaps": "^2.6.4",
    "gulp-uglify": "^3.0.1",
    "gulp-uglifycss": "^1.1.0",
    "gulp-sort": "^2.0.0",
    "gulp-wp-pot": "^2.3.2"
  }

**Comment by ahmadawais** [comment]
Doesn't look like an issue or a PR.

Here's the latest Branch https://github.com/ahmadawais/WPGulp/tree/v2.0.0

**Comment by WPGulpPro** [comment]
When are you going to update your dependencies? WPGulp is extremely outdated. Why?
