### ISSUE TITLE
ERROR: Cannot find module 'babel-preset-env' - Did you mean "@babel/env"?

### ISSUE THREAD

**Issue by justlevine** [ahmadawais/WPGulp#109]
### Actual Behavior

When runining `npm start` I get several errors:
`❌  ===> ERROR: Cannot find module 'babel-preset-env' from 'D:\www\boldcreative\wp-content\themes\boldcreative'
- Did you mean "@babel/env"?`

### Steps to Reproduce

1. Deleted node_modules, and any 1.9.x WP_Gulp files (package.json, config, etc).
2. Run `npx install-wpgulp` and configure new wpgulp.config.js
3. Run `npm start`

1. `node -v`: v8.11.1
2. `npm -v`: 5.6.0

Then, specify:

1. Operating system:
2. Browser and version (if relevant):

**Possible Solution**
run `npm install babel-preset-env`

**Comment by ahmadawais** [comment]
You shouldn't be using 1.9.x files with `install-wpgulp` you should be using the latest files. 

It's my understanding that `install-wpgulp` should overwrite all the simular files in the current directory.

Thoughts! 👌

**Comment by justlevine** [comment]
Thats why I said 'deleted... and **any 1.9.x. WP_Gulp files**'. I assumed it would overwrite it all, but JIC once i got this error, I made sure to manually delete everything before `install-wpgulp`

**Comment by ahmadawais** [comment]
By going through all the steps for reproducing the error I didn't get an error. You must have some different env where this error came from. Think and let me know.

I am thinking that a rename of all the old files by the installer would also be a good next step.

**Comment by siriusnottin** [comment]
I have the same error 😅I think I did a bad update of WP Gulp, could it be that?

**Comment by ahmadawais** [comment]
@siriusnottin I am unable to reproduce this issue at my end. Explain.

**Comment by siriusnottin** [comment]
Sorry for the lack of explanation 😇 I deleted the node_modules folder, the package.json, package-lock.json and gulpfile.js files.
After following the readme.me I run `npm install` and `npm start` after, this error was displayed and my javascript files are no longer taken into account in the vendor and custom folder :

❌  ===> ERROR: Cannot find module 'babel-preset-env' from '/Users/siriusnottin/Sites/lacavedujazz.fr/site/web/app/themes/lacavedujazz'
- Did you mean "@babel/env"?

**Comment by ahmadawais** [comment]
Sounds like you probably have a `.babelrc` that is still referencing `babel-preset-env`. Can you both confirm if you have a pre-existing `.babelrc` or similar file?

**Comment by ahmadawais** [comment]
OK, I think I know what the issue was. 

Gulp file needed new `'@babel/preset-env'` syntax upgrade. Just released a new version for both WPGulp and installer. Try now.

**Comment by siriusnottin** [comment]
Great, it works 👌, thank you so much @ahmadawais ! it was my first bug report on GitHub btw 😂

**Comment by ahmadawais** [comment]
Ha. Now step it up and contribute for the next milestone. 👌
