### ISSUE TITLE
[RESOLVED] printNextSteps is not a function (FIXED v2.6.0)

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/WPGulp#111]
There was an error in the `printNextSteps`  file where I accidentally commented out the module.exports. That resulted in an error like this:

```sh
npm/_npx/1103/lib/node_modules/wpgulp/installer/index.js:34
        throw err;
        ^

TypeError: printNextSteps is not a function
```

So, it was fixed in `v2.6.0`. It may take a while for `npx` to pick it up but you can test `npx wpgulp@2.6.0` and it works. But mostly you should be fine with just `npx wpgulp` in an hour after the release.

Thanks for the report Shamai.

**Comment by ahmadawais** [comment]
Just tested `npx wpgulp` and it's working fine.

**Comment by saltnpixels** [comment]
hmmm for some reason it wont work on one of my macs. I get this error when i try to run npx wpgulp:

## Bug Report
```
throw err;
      ^
Error: Command failed: npm install --silent
```

Node: 8.12
NPM: 6.4.1


Then, specify:

1. Operating system: Mac OS 10.13.6
