### ISSUE TITLE
Error installing, command failed

### ISSUE THREAD

**Issue by saltnpixels** [ahmadawais/WPGulp#112]
## Bug Report
I get an error when I try and install it
The error is 
  ```
 throw err;
        ^
Error: Command failed: npm install --silent

```

I am using the latest versions of node and npm.
I am on a Mac OS

**Comment by ahmadawais** [comment]
@saltnpixels still having this issue? Kindly report through the original bug report issue and answer all the questions there so that I know which version of what you are using 👍 Just copy paste the template from a new issue below :).

Looking forward!

**Comment by ahmadawais** [comment]
`npm install --silent` should work. Can you test `npm install --silent wpgulp` on that computer to see if it has an npm issue?

**Comment by saltnpixels** [comment]
So `npm install --silent wpgulp` does work.
But when I run npx wpgulp the issue still comes up.
Error:
```
Installing npm packages.../Users/ericgreenfield/.npm/_npx/8327/lib/node_modules/wpgulp/installer/index.js:34
        throw err;
        ^

Error: Command failed: npm install --silent


    at makeError (/Users/ericgreenfield/.npm/_npx/8327/lib/node_modules/wpgulp/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/ericgreenfield/.npm/_npx/8327/lib/node_modules/wpgulp/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by ahmadawais** [comment]
It looks like `npm install --silent` command is failing. This could also be a permissions issue. Can you run `sudo npx wpgulp` and report back?/

**Comment by saltnpixels** [comment]
Even with sudo it fails. :/

**Comment by ahmadawais** [comment]
Can you try the beta? Run:

```sh
npx wpgulp@2.6.1-beta.0
```

and report back?

**Comment by saltnpixels** [comment]
Here are the errors from using 2.6.1-beta

```
Installing npm packages.../Users/ericgreenfield/.npm/_npx/8953/lib/node_modules/wpgulp/installer/index.js:34
        throw err;
        ^

Error: Command failed: npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN your-project@1.0.0 No repository field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ericgreenfield/.npm/_logs/2018-09-14T14_33_30_023Z-debug.log


    at makeError (/Users/ericgreenfield/.npm/_npx/8953/lib/node_modules/wpgulp/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/ericgreenfield/.npm/_npx/8953/lib/node_modules/wpgulp/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by saltnpixels** [comment]
I was able to run it successfully on another computer. 
Then I copied it to the problem computer and tried running npm start.

Here is the error I get when i do that:
```
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-cli'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ericgreenfield/Dropbox/projects/sites/ignition/app/public/wp-content/themes/ignition/node_modules/.bin/gulp:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! your-project@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the your-project@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ericgreenfield/.npm/_logs/2018-09-14T15_14_06_428Z-debug.log

```

Does that help at all?

I tried updating npm, node and gulp on the global level but still it wont work right.

**Comment by ahmadawais** [comment]
Well, it's definitely your computer's issues. Coz now it's not installing modules from `npm install`. I thought maybe `--silent` was casuing it. 

My guess is [create-guten-block](https://github.com/ahmadawais/create-guten-block) would also not work on your problem computer. Can you try that and report back. Coz. it works for everyone and I am using the same installer for WPGulp.

Looking forward!

**Comment by ahmadawais** [comment]
Also, latest version of WPGulp doesn't require a global installation of `gulp`. That caused issues in the previous versions.

**Comment by saltnpixels** [comment]
I deleted the node_modules folder and everything and started over and now it works... im confused...
Maybe updating gulp helped? But you said it didn't need to be installed globally.
I dunno....

Now I will test it on the other computer where it was working before!

**Comment by ahmadawais** [comment]
For sure it was an issue of your npm's permissions inside the node-modules. Can you now try the regular one i.e. `npx wpgulp` and report back before we close this. I'll add it to FAQs.

**Comment by saltnpixels** [comment]
Yes the regular npx wpgulp did work.  
Thanks.  

--  
Eric Greenfield

**Comment by ahmadawais** [comment]
That's it then. I'll add `remove node_modules` to the list of upgrade method.

**Comment by jurdanetacom** [comment]
Hi @saltnpixels , I'm having the same exact problem than you:

In the directory: E:\temp\npmtest4
 This might take a couple of minutes.

√ 1. Creating WPGulp files inside →  E:\temp\npmtest4
\ 2. Installing npm packages...C:\Users\CH3\AppData\Roaming\npm-cache\_npx\8600\node_modules\wpgulp\installer\index.js:34
        throw err;
        ^

Error: Command failed: npm install --silent


    at makeError (C:\Users\CH3\AppData\Roaming\npm-cache\_npx\8600\node_modules\wpgulp\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\CH3\AppData\Roaming\npm-cache\_npx\8600\node_modules\wpgulp\node_modules\execa\index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

I read that you deleted "node_modules", so I uninstalled Node, and deleted 
\AppData\Roaming\npm-cache\ and \AppData\Roaming\npm\ folders, then reinstalled node.js but then 
I'm getting the same error.

Is there any other folder I'm missing?

Thanks

NPM: 6.4.1
NODE: 8.12.0
Windows 10

**Comment by ahmadawais** [comment]
@jurdanetacom can you delete the `node_modules` folder inside your project and run `npm install` again?

**Comment by jurdanetacom** [comment]
@ahmadawais there isn't a `node_modules` folder inside the project folder, you mean in \AppData ?

**Comment by tarfoot** [comment]
I'm having the same issue with `npx start` even when starting in a completely empty folder.
But `npm install --silent wpgulp` works.

NODE: 10.12.0
NPM: 6.4.1
MACOS: 10.12.6

-----------------------------------
running `npx wpgulp`:

Downloading WPGulp files in: →  tmp 
 
 In the directory: /Users/bradley/Sites/clients/tmp
 This might take a couple of minutes.

✔ 1. Creating WPGulp files inside →  tmp 
⠴ 2. Installing npm packages.../Users/bradley/.npm/_npx/53976/lib/node_modules/wpgulp/installer/index.js:34
	throw err;
	^

Error: Command failed: npm install --silent


    at makeError (/Users/bradley/.npm/_npx/53976/lib/node_modules/wpgulp/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/bradley/.npm/_npx/53976/lib/node_modules/wpgulp/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

-----------------------------------
running `npm install --silent wpgulp`:
\+ wpgulp@2.6.0
added 143 packages from 70 contributors and audited 280 packages in 3.224s
found 0 vulnerabilities

**Comment by parys-github** [comment]
Hi guys.
I have exactly the same problem.
After running: npx wpgulp it receives a message:
======================================================================
2. Installing npm packages.../Users/me/.npm/_npx/23630/lib/node_modules/wpgulp/installer/index.js:34
        throw err;
        ^

Error: Command failed: npm install --silent

 at makeError (/Users/me/.npm/_npx/23630/lib/node_modules/wpgulp/node_modules/execa/index.js:174:9
    at Promise.all.then.arr (/Users/me/.npm/_npx/23630/lib/node_modules/wpgulp/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=======================================================================
NPM: 6.4.1
NODE: v10.12.0
MAC OSX: 10.13.6

Trying to use solutions suggested above but no positive results unfortunately :-/

**Comment by ahmadawais** [comment]
Several folks were having same issues on Windows — some folks reported updating npm to the latest version fixed it. `npm install --silent` is failing for some reason.

**Comment by Nervez** [comment]
> Several folks were having same issues on Windows — some folks reported updating npm to the latest version fixed it. `npm install --silent` is failing for some reason.

I'm on windows as well, having the same issue, even after updating npm to the latest version.

**Comment by lushkant** [comment]
Having the same problem as the guys above on Windows 10.
Tried both node 8 and 10 but it didn't make any difference. I did follow up with the conversation here but doing so didn't help! :(

**Comment by gamanox** [comment]
damn, it's there any workaround? thanks a lot, I tried everything in this conversation

**Comment by berlindave** [comment]
Same Problem here:  With `npx install` I get:

```
2. Installing npm packages.../Users/dave/.npm/_npx/9692/lib/node_modules/wpgulp/installer/index.js:34
	throw err;
	^

Error: Command failed: npm install --silent


    at makeError (/Users/dave/.npm/_npx/9692/lib/node_modules/wpgulp/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/dave/.npm/_npx/9692/lib/node_modules/wpgulp/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
`npm install --silent` is working.

NPM: 6.4.1
NODE: v10.12.0
MAC OSX: 10.11.6

Any suggestions?

**Comment by tarfoot** [comment]
I think this is solved if you change the reference to gulp in package.json.
It solved it for me anyhow. It does involve running `npm install` after `npx wpgulp` fails.

See issue #128 and the fix in #129

**Comment by ahmadawais** [comment]
Sorry, folks! I have been super busy. Looks like the latest `npm` had issues with `gulp` and now the recommended way to use gulp 4.0 is to write just that. Thanks @tarfoot for the PR #129 this should now be fixed.

**Comment by elliottmangham** [comment]
Hello, I seem to be having this issue (https://github.com/ahmadawais/WPGulp/issues/207).

I tried running `npx wpgulp`  and then after it fails, running `npm install`, but this also errors.

- npm @ 8.5.0
- node @ 16.14.2

Would really love any help, thank you

**Comment by elliottmangham** [comment]
Here's a screen of running `npm install` after `npx wpgulp`, where you can see it failing:
![image](https://user-images.githubusercontent.com/12933804/164396299-ff0e9cbf-9f11-416b-b106-7a2e6ba3e2cd.png)

Would be happy to pay for support on this, as I'd love to get WPGulp working - assuming it is still maintained anyway.

Thanks!

**Comment by ahmadawais** [comment]
Honestly, I haven't had much time lately to support this project for free. Will see if I can set some time aside if I get some support — with everything going on atm. Thank you! 🙌

**Comment by elliottmangham** [comment]
Thanks so much @ahmadawais, it's appreciated greatly. And as I said, I'm happy to pay for the [Paddle contribution](https://pay.paddle.com/checkout/515568).

**Comment by elliottmangham** [comment]
Hey, so I decided to buy a brand-new Mac and attempt to get WPGulp running, since I had issues on my Windows machine.  Unfortunately, I seem to have similar issues on this also (MacBook Pro 2021 model with M1 Pro chip) as well.

Below is my error log after running `npx wpgulp`:
[log.txt](https://github.com/ahmadawais/WPGulp/files/8558421/log.txt)

Would love some help and insight, thank you.

**Comment by ahmadawais** [comment]
@ahmadbilaldev an excellent opportunity to contribute.
