### ISSUE TITLE
Cannot find module 'babel-preset-env' from ...

### ISSUE THREAD

**Issue by robmim** [ahmadawais/WPGulp#116]
Since i moved to gulp 4 i can't build vendor and custom js file because of this. 

❌  ===> ERROR: Cannot find module 'babel-preset-env' from '/Applications/MAMP/htdocs/eranum/wp-content/themes/eranum'
- Did you mean "@babel/env"?

**Comment by robmim** [comment]
Ah nevermind. I recreated the setup after upgrading to gulp4. Everything is now fine.

Sorry Ahmad ;)

**Comment by ahmadawais** [comment]
Yes, just reinstall the latest version. You should be fine. It was an earlier error in v2.4 I think. Everything related to babel is not namespaced with `@babel` for obvious reasons after v7.
