### ISSUE TITLE
Adding js files to vendor folder like on the wpgulp V1 doesnt seem to work

### ISSUE THREAD

**Issue by robmim** [ahmadawais/WPGulp#117]
In version 01 of WPGULP :

I simply drop a js file into the vendor folder and it will be concatenated into a single JS file name vendor.js using the command : GULP

But in version 02, using GULP or NPM START doesnt seem to work. Always get the error:

Uncaught TypeError: Cannot set property 'js-filename-in-vendor-folder' of undefined

GULP, NODE and NPM version
https://www.dropbox.com/s/hv26fhwks4nky0m/Capture%20d%27%C3%A9cran%202018-09-21%2017.18.03.png?dl=0

Console errors
https://www.dropbox.com/s/x8nc4upf51fc3ot/Capture%20d%27%C3%A9cran%202018-09-21%2016.56.28.png?dl=0

functions.php
https://www.dropbox.com/s/wygmqimj441rc6z/Capture%20d%27%C3%A9cran%202018-09-21%2016.57.39.png?dl=0

wpgulp.config.js
https://www.dropbox.com/s/kt5yxvlo69xo0o5/Capture%20d%27%C3%A9cran%202018-09-21%2017.07.24.png?dl=0

I tried with the version 01 setup and its worinking fine but in version 02, nothings work.

What am i doing wrong ????

**Comment by robmim** [comment]
Do not have others choice to rollback to version 01 until i get this fix.

**Comment by ahmadawais** [comment]
That console log error shows that one of the vendor scripts you are using is causing a problem and with that I can't help. For my tests the vendors file worked just fine. You should be enqueueing the `.min.js` files for both vendor and custom.

**Comment by robmim** [comment]
The vendors files i'm using are :


Barba.js
https://github.com/luruke/barba.js

Hunt.js
https://github.com/jeremenichelli/hunt

**Comment by ahmadawais** [comment]
Can you point me to a sample directory where I can test WPGulp with your vendor scripts?

**Comment by bilalmalkoc** [comment]
I have same problem. When i concatenate with true order (ie. jquery -> popper -> bootstrap) vendor.js sows console error.

**Comment by ahmadawais** [comment]
I am open to a PR that fixes this issue. Unable to find more time this week.

**Comment by bilalmalkoc** [comment]
Is that fixed? I can't see in PR.

**Comment by robmim** [comment]
Hi @ahmadawais,

There an article that explain the issue here

https://stackoverflow.com/questions/51307582/barba-is-not-defined-error

**Comment by mykt0ngc0** [comment]
It appears that some vendor files don't go well with gulp-babel. 

Commenting out the `babel` `pipe` on `vendorsJS` `task` does the trick for me. 👇

![untitled](https://user-images.githubusercontent.com/14344154/53683248-8ed0f580-3d39-11e9-82dd-309dd4798361.png)


Source: [**prncdahal**](https://github.com/ahmadawais/WPGulp/issues/136#issuecomment-453372574) on issue #136

**Comment by robmim** [comment]
@mykt0ngc0 indeed this work great. Thanks !!!

**Comment by kleytoncaires** [comment]
> It appears that some vendor files don't go well with gulp-babel.
> 
> Commenting out the `babel` `pipeline` on `vendorsJS` `task` does the trick for me. 👇
> 
> ![untitled](https://user-images.githubusercontent.com/14344154/53683248-8ed0f580-3d39-11e9-82dd-309dd4798361.png)
> 
> Source: [**prncdahal**](https://github.com/ahmadawais/WPGulp/issues/136#issuecomment-453372574) on issue #136

doesnt work for me
