### ISSUE TITLE
Browser Sync not working

### ISSUE THREAD

**Issue by jerrylee** [ahmadawais/WPGulp#118]
I love this, just one question, I have set it up, and modified the path to my localhost, and my SASS path. It creates the proper css file, but does not auto reload the browser. Thanks for this cool software.

**Comment by ahmadawais** [comment]
Glad you liked it. I'll need much more info then this. You have to use the bug report template template of issue and answer all questions. 

What did you do, what changes you made, etc. What tools you used.

**Comment by ahmadawais** [comment]
Closing it, kindly file with the bug template.
