### ISSUE TITLE
Error watching files for changes: UNKNOWN

### ISSUE THREAD

**Issue by carlosnpz** [ahmadawais/WPGulp#122]
Hey guys!
I've successfully installed WPGulp, but when I run "gulp" command, I get the following message:

anonymous errored after 4.08s
Error: Error watching files for changes: UNKNOWN 
at _errnoException (util.js:992:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)

Can anyone help me solving this?

**Comment by ahmadawais** [comment]
You have to file a bug with all the info that's asked of you in the template without that it's impossible for anyone to help you. Also make sure you follow the docs https://github.com/ahmadawais/WPGulp#getting-started
