### ISSUE TITLE
custom.js and vendor.js files are not executed with "use strict"; on the top of "Gulped" files.

### ISSUE THREAD

**Issue by parys-github** [ahmadawais/WPGulp#132]
Hi guys.
I started working with WPGulp a few weeks ago and in my two previous projects, everything works perfectly.  Unfortunately, in the current project, I have a very frustrating problem. Every time when compiling JS files at the beginning of the code an extra line is added: **"use strict";**

This causes my JS files not to be executable. When I manually remove **"use strict";** from production files,  then everything works perfectly as I expect, I mean that all JS files work correctly on all browsers and in all expected mobile devices.
It is not a big deal to remove **"use strict";** from the final file **vendor.min.js** because during the work with the project I do not edit these files anymore. But I am editing constantly the **custom.js** file and delete **"use strict";** every time it is bothersome.

My question is: is it possible to force Gulp/Babel not to add the **"use strict;"** line; to the compiled code?
I mean, for example, extra feature in wpgulp.config.js  something like **use-strict: false/true**?
I admit that I tried solutions:
[https://github.com/azu/gulp-remove-use-strict](https://github.com/azu/gulp-remove-use-strict) or
[https://github.com/genify/babel-plugin-transform-remove-strict-mode](https://github.com/genify/babel-plugin-transform-remove-strict-mode) but I did not get positive results :-/

Node: v10.12.0
NPM: 6.4.1
Operating system: MacOS 10.13.6
All popular browsers.

I will be grateful for any suggestions.
Cheers

**Comment by parys-github** [comment]
If anyone has any ideas how to fix that troublesome problem please let me know?

**Comment by mykt0ngc0** [comment]
Try this simple trick here 👉 https://github.com/ahmadawais/WPGulp/issues/117#issuecomment-468925970

**Comment by ametthey** [comment]
It's not working for me! :( any other solutions ?

**Comment by CatinhoCR** [comment]
Having this issue when trying to import jquery

**Comment by parys-github** [comment]
Seams to be OK.
