### ISSUE TITLE
It automatically including bootstrap js code in vendor.js file while there's no bootstrap.js file in vendor folder. 

### ISSUE THREAD

**Issue by prncdahal** [ahmadawais/WPGulp#137]
![image](https://user-images.githubusercontent.com/9000998/50959429-0da07380-14eb-11e9-8d4f-1b873b343f9c.png)

**Comment by wowthemesnet** [comment]
I'd rename the vendor files with the order I want:
1-popper.min.js
2-bootstrap.min.js

Then `npm start` again.
