### ISSUE TITLE
Translate is not running

### ISSUE THREAD

**Issue by saltnpixels** [ahmadawais/WPGulp#140]
## Bug Report
I noticed the translate task is not set up to run. Not sure if this is on purpose?
### Expected Behavior
Well it should compile into a languages folder.

### Actual Behavior
Nothing happens

**Comment by ahmadawais** [comment]
You have to share what you ran in the actual behavior heading instead of saying it doesn't work. 

Did you try and read this

https://github.com/ahmadawais/WPGulp/blob/master/README.md#-optional-step-4--more-scriptstasks

**Comment by saltnpixels** [comment]
Ah. So translate is not set to be watched?
I have to run gulp translate.
I figured it was by mistake missing from the gulp is file because it was not compiling when the php files changed.

Eric Greenfield

**Comment by ahmadawais** [comment]
It's a good practice to read to docs b3fo5re issues to see if it was intentional 😂
