### ISSUE TITLE
Comment header in compiled styelsheet does allow WP to recognize theme

### ISSUE THREAD

**Issue by claytoncollie** [ahmadawais/WPGulp#144]
Hi there. Getting started with WP Gulp and really like it. Thank you very much for your hard work.

I was pulling my hair out trying to figure out why I could not load my page templates when creating a post, then I remembered that the style.css and style.min.css files change the comment header when in `compact` mode.  

Is this normal behavior? Is there a way to get a compact stylesheet without it touching the comment header?  Thanks in advanced for the insights.

**Comment by ahmadawais** [comment]
That's very kind of you to say! 🙌

Nice catch. Your theme comment should have a `!` in it to be not removed.

Just start your theme comment block like this.

```css

/*!
Theme Name: WPGulpTheme
…
```

**Comment by ahmadawais** [comment]
If you like my work, consider supporting it by purchasing [VSCode Power User Course →](https://VSCode.pro)

**Comment by claytoncollie** [comment]
Thanks for that. I already have the exclamation.

The comments are there and always have been. It is not that it is being removed. it is being minified which is causing the error/ WP not being able to read it properly.

**Comment by ahmadawais** [comment]
Comments are not minified after you add a `!` bang sign. Without you sharing more like code and all with what you see on your end I can't say much.

**Comment by danderozier** [comment]
For anyone else who comes across this issue — in order to preserve the commend _and_ avoid minification, specific formatting is required. Each line must start at the beginning of the line; any spaces or asterisks included before each line will cause SASS to minify the comment.

This works:
```
/*!
Theme Name: My Theme
Author: Daniel Derozier
*/
```

These do not work:
```
/*!
  Theme Name: My Theme
  Author: Daniel Derozier
*/

/*!
 * Theme Name: My Theme
 * Author: Daniel Derozier
*/
```

**Comment by claytoncollie** [comment]
Thanks @danderozier for the extra info. Very much appreciated.
