### ISSUE TITLE
Disable notifications like "STYLES - completed!"

### ISSUE THREAD

**Issue by asmundsollihogda** [ahmadawais/WPGulp#155]
Thank you for creating this great asset for a minimalistic wordpress workflow. I've just started using it and are very happy.

I was wondering if there is a simple way to prevent my mac os notifications for successful CSS etc? I have tried to remove the line:
`.pipe( notify({ message: '\n\n✅  ===> STYLES — completed!!\n', onLast: true }) );`
...from gulpfile.babel.js without success. Nothing is happening like this file is not in use?

Thank you again for creating WPgulp

**Comment by kevinhuddy** [comment]
Hi @asmundsollihogda you need to re-run npm start after removing some code to wpgulp for it to take action.

**Comment by asmundsollihogda** [comment]
Thanks @kevinhuddy, that works like a charm :)
