### ISSUE TITLE
Changes in SCSS files not recompiling & injecting in to browsers

### ISSUE THREAD

**Issue by ashbryant** [ahmadawais/WPGulp#158]
### Expected Behavior

Changing .scss file content & saving would trigger a recompile of styles and an injection into the browser(s).

### Actual Behavior

npm start compiles all files, changes to scss files after doesn't update changes. All other files being watched are working recompiled as expected

### Steps to Reproduce

wpgulp.config.js
`// Style options.
	styleSRC: './assets/scss/style.scss', // Path to main .scss file.
	styleDestination: './dist/css/', // Path to place the compiled CSS file. Default set to root folder.
	outputStyle: 'compressed', // Available options → 'compact' or 'compressed' or 'nested' or 'expanded'
	errLogToConsole: true,
	precision: 10,`

scss structure

assets/scss/style.scss - Main .scss file
assets/scss/elements/nav.scss - imported in to style.scss

node = v8.11.1
Operating system = macOS Mojave v 10.14.6
Browser = any

**Comment by AndreaBarghigiani** [comment]
Hi @ashbryant why did you close this issue? Have you solve it?

I usually work with WPGulp but lately I have your same issue. Even if I edit my main `style.scss` file it looks to me that Gulp does not watch my changes.

How did you solve it?

**Comment by jeffceriello** [comment]
Same issue here. Since I've moved to a M1 silicon mac Gulp doesn't look for changes anymore
