### ISSUE TITLE
Sourcemaps are written in nested directory

### ISSUE THREAD

**Issue by joshlevinson** [ahmadawais/WPGulp#16]
Per the [documentation](https://www.npmjs.com/package/gulp-sourcemaps) of gulp-sourcemaps, when writing to an external sourcemap file, the path provided to `sourcemaps.write()` should be _relative_ to the path of the source file(s) destination.
The config of this project uses `styleDestination` for the `sourcemaps.write()` destination, meaning it gets nested within incorrectly created subdirectories.
The fix for this is to simply provide `./` as the sourcemap destination, meaning it will get created alongside the compiled files.

**Comment by ahmadawais** [comment]
@joshlevinson What if the style destination is not the root folder? What then?

**Comment by ahmadawais** [comment]
Still waiting for your response. Closing it down till then.

**Comment by ahmadawais** [comment]
Closing down the issue because of no response.

**Comment by selrond** [comment]
@joshlevinson @ahmadawais This is now fixed by https://github.com/ahmadawais/WPGulp/pull/59

**Comment by ahmadawais** [comment]
@selrond Thanks for that 👍
