### ISSUE TITLE
how to configure project variables to compile from multiple SASS directories

### ISSUE THREAD

**Issue by arnoldbird** [ahmadawais/WPGulp#162]
I'm having trouble getting started with WPGulp.  Have installed it successfully, but it's not clear how to do step 2 in the README, "Editing the Project Variables."

I can get my main style.scss file to compile to style.css, but this is not very useful.  I need gulp to compile multiple SCSS files into my style.css.

My directory structure is like...

my_theme/style.css
my_theme/sass/style.scss
my_theme/sass/subdirectory/_example.scss
my_theme/sass/subdirectory2/_example2.scss
etcetera

How do I get all the SCSS files to compile to my_theme/style.css?

This doesn't seem to work:
`
styleSRC: './sass/style.scss', 
styleDestination: './', 
watchStyles: './sass/**/*.scss',
`

Thanks.

**Comment by robmim** [comment]
Why not simply include thoses subdirectory files inside your style.scss and then set your style.scss as primary source for your css ?

**Comment by ahmadawais** [comment]
Import all these files in one single `styles.scss` file. That should do it.

**Comment by arnoldbird** [comment]
Thanks!  That's it exactly.
