### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by CatinhoCR** [ahmadawais/WPGulp#186]
First of all thanks for this project. I've used a few times to setup some small projects and it's great starting point.. With that said,

I'm pretty sure this is quite an extensive project to keep up to date by one person, or even a small team. Im also pretty sure there's many people like me who would love to help out around maintaining it.. Im not sure what the goals, intentions or current project's state are but just wanted to get ask.

Thanks

**Comment by jeni1616** [comment]
May be try contact author via https://twitter.com/MrAhmadAwais/

**Comment by ahmadawais** [comment]
Hi @CatinhoCR 
This project is close to my heart because it was one of oldest open source projects. I try my best to maintain it but I have over 200 open source projects. 

There are multiple ways you can help me with that. 

1. [Buy my courses of sponsor my work](https://github.com/AhmadAwais/sponsor)
2. Help out by managing the repo, triaging issues, and building/improving code

Let me know.

**Comment by CatinhoCR** [comment]
> Hi @CatinhoCR
> This project is close to my heart because it was one of oldest open source projects. I try my best to maintain it but I have over 200 open source projects.
> 
> There are multiple ways you can help me with that.
> 
> 1. [Buy my courses of sponsor my work](https://github.com/AhmadAwais/sponsor)
> 2. Help out by managing the repo, triaging issues, and building/improving code
> 
> Let me know.

Sorry I lost track of this, appreciate man. Your project has served me well for a long time. I was thinking about helping you maintain this back when I posted this but things have took me on a different direction since then and I'd rather not commit myself since time is tight lately in here.
Again though, thanks for making this and sharing it ! It saved me quite a few times.

Would you be open to porting this to a more webpack based workflow?
