### ISSUE TITLE
Add a build/deploy functionality

### ISSUE THREAD

**Issue by jamieschmid** [ahmadawais/WPGulp#188]
**Is your feature request related to a problem? Please describe.**
After developing, you need to remove a lot of files, and zip the folder in order to upload to WP if you are doing a manual process. This means removing sass folder, any compiler files, node_modules, maybe a docs folder etc. A way to deploy a production build within a new directory would complete this tool I believe! 

**Describe the solution you'd like**
- Be able to define which folders/files you want excluded from the deploy
- Identify what you want to run on build: concatenate, minify, etc. I typically use non-minified versions during dev, but need minified files in the deploy version. 
- Auto zip the deploy folder once it's done

There's some existing PR's for this you can review also-

Deploy script generates zip file PR:
https://github.com/ahmadawais/WPGulp/pull/143

PR using gulp-if and gulp-clean to run a deploy
https://github.com/ahmadawais/WPGulp/pull/135

**Comment by ahmadawais** [comment]
I'm looking into this as a solution that does the following:

- Allows you to zip the directory
- Define the path where the zip is placed afterward
- Define things to ignore in the zip file

Is that it?

**Comment by ahmadawais** [comment]
Finally got some time to do this:

New configurable zip settings https://github.com/ahmadawais/WPGulp/blob/master/WPGulp/wpgulp.config.js#L79-L110

V3 Release notes: https://github.com/ahmadawais/WPGulp/releases/tag/3.0.0

Major refactor and also updated the demo [WPGulpTheme](https://github.com/ahmadawais/WPGulpTheme)

Please test it and enjoy the v3 release.

**Comment by lopezs** [comment]
Hi @ahmadawais thank you for your work on this, but I'm not sure how to run a task to do it. 

I don't see anywhere in the source code where zip related settings are actually referenced.
