### ISSUE TITLE
Using Tunnel in the browser-synch function in gulpfile.js doesn't work

### ISSUE THREAD

**Issue by robmim** [ahmadawais/WPGulp#19]
How can i make the tunnel options working using Browser-synch ?

I saw you had the same problem here : https://github.com/BrowserSync/browser-sync/issues/978

The error i got is :

/Applications/MAMP/htdocs/CNM/wp-content/themes/cnm/node_modules/browser-sync/lib/browser-sync.js:665
    bs.io.sockets.emit("file:reload", data);
         ^

TypeError: Cannot read property 'sockets' of undefined
  at BrowserSync.doFileReload (/Applications/MAMP/htdocs/CNM/wp-content/themes/cnm/node_modules/browser-sync/lib/browser-sync.js:665:10)

**Comment by ahmadawais** [comment]
Yes, this is not the issue with this script. It's BrowserSync where you should report it :) I think the dev is working on it for the next version.
