### ISSUE TITLE
Licensing issue – MIT or GPLv2?

### ISSUE THREAD

**Issue by redtux** [ahmadawais/WPGulp#196]
Thank you for this awesome project! :heart_eyes: 

I see you are committing a lot lately, so I am curious to test your changes soon (e.g. the zip task). :tada: 

Just one question regarding WPGulp's current license: Is the code subject to MIT or GPLv2?

GitHub and the [license.md](https://github.com/ahmadawais/WPGulp/blob/master/license.md) file say it is released under the GPLv2, while the [readme.md](https://github.com/ahmadawais/WPGulp/blob/master/readme.md#license--attribution) and the [package.json](https://github.com/ahmadawais/WPGulp/blob/master/package.json) files state it is MIT licensed. Could you please fix this?

I am comfortable with both, but I would like to know which one is correct. Thanks a lot! :+1:

**Comment by ahmadawais** [comment]
Fixed to MIT.
