### ISSUE TITLE
Zip task is missing? 

### ISSUE THREAD

**Issue by marcinkrzeminski** [ahmadawais/WPGulp#197]
## Bug Report

I'm getting an error while trying to run the `npm run zip` task. It looks like the task is not defined at all in the `gulpfile.babel.js`. Am I missing something here?

### Expected Behavior

Based on the documentation and config file it should create a `theme.zip` file.

### Actual Behavior

Gulp / Node throws an error

### Steps to Reproduce

Just try to run `npm run zip` or `gulp zip`

1. `node -v`: 14.12.0
2. `npm -v`: 6.14.8
3. `yarn --version` (if you use Yarn): 1.22.5

Then, specify:

1. Operating system: macOS 11.0.1

**Possible Solution**

In `gulpfile.babel.js` import the `gulp-zip`:

```
const zip = require('gulp-zip');
````

Add a task that does the zip:

```
gulp.task('zip', () => {
	const src = config.zipIncludeGlob.concat(config.zipIgnoreGlob);
	return gulp
		.src(src)
		.pipe(zip(config.zipName, {}))
		.pipe(gulp.dest(config.zipDestination));
});
```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I can submit a PR if you'd like me to :)

**Comment by ahmadawais** [comment]
Whaaaat? How the heck did I miss that. Where did the code go? I remember writing the function but it's not there lol. Thanks for the report. I just codded it again.


🔗 https://github.com/ahmadawais/WPGulp/releases/tag/3.1.0
🔗 https://www.npmjs.com/package/wpgulp
