### ISSUE TITLE
Just a fun suggestion. Add wapuu or WordPress logo to the notification.

### ISSUE THREAD

**Issue by josephfusco** [ahmadawais/WPGulp#2]
Would look something like:
```javascript
.pipe( notify( { message: 'TASK: "vendorsJs" Completed!', icon: "wapuu.png", onLast: true } ) );
```
I guess it wouldn't really make sense since it would add a file. Although could probably serve up an icon from outside the repo. Although this is meant to be a boilerplate it would be pretty neat.

**Comment by ahmadawais** [comment]
@josephfusco I'll take it under-advisement to see if anything could be done 👣:)
