### ISSUE TITLE
Watch commands taking too much time within Default task

### ISSUE THREAD

**Issue by imfaisalkh** [ahmadawais/WPGulp#20]
I'm using WPGulp build script as a base and I've noticed that when I run the `default` gulp task by running `gulp` command, each of the dependent task took time in a few milli seconds to finish  but still the `default` task is taking 4-8 minutes to finish, I tried commenting out `watch` commands within the `default` task and turns out these commands were causing all this delay.

How to resolve this? Is it machine specific issue?

**UPDATE:** The real culprit is `projectPHPWatchFiles` watch command. If I comment out only this command the build time decreased to only 15 seconds.

PS: My laptop has 4 GB of RAM and 1.7Ghz i3 processor.

**Comment by ahmadawais** [comment]
@imfaisalkh I am not sure you understand the default behavior. The default task is not a build task. It builds everything and then it sits there to watch for any changes that you might make. While you are developing, this should be watching your files. Once you are done with dev you can press <kbd>CTRL</kbd> + <kbd>C</kbd> to quit this task.

**Comment by imfaisalkh** [comment]
I do understand the behaviour, perhaps I've not explained it clearly. The `default` task is taking too much time to "finish", here the word "finish" means when the console prints `Finished 'default' after 5.48 min`, after this it starts watching files and provide a preview URL.

This task do "watch" the files at the end, but it is taking too much time to get there. As mentioned earlier `projectPHPWatchFiles` watch command is seems to be the real culprit.

**Comment by ahmadawais** [comment]
@imfaisalkh Must be your slow computer than. It's pretty weird though. I will soon push an update.

**Comment by imfaisalkh** [comment]
I've tried narrowing down the PHP file selection criteria, like this:

`var projectPHPWatchFiles    = ['./**/*.php', '!./.git/**/*', '!./.dist/**/*', '!./.vendors/**/*', '!./node_modules/**/*', '!./styles/**/*', '!./scripts/**/*', '!./languages/**/*', '!./images/**/*', '!./fonts/**/*']; // Path to all PHP files.`

Now, as per this criteria, there is almost 25-30 `php` files to watch in the theme folder but still watch command is taking almost 5 mins now.

I've not tested this script in my main computer but 4GB ram should suffice for such small number of files and CPU usage during script execution is very low, so CPU shouldn't be the bottleneck either.

**Comment by ahmadawais** [comment]
Takes 1.4sec on my end with Macbook 16 GB RAM :)

**Comment by imfaisalkh** [comment]
Just tested the script on another computer (core i5 3.3Ghz + 4 GB Ram), the `default` task took about 35sec, so apparently, it is the system specific issue. However, I'm not sure why the script is not using the idle CPU power on my laptop to improve the execution time. Nevertheless, it doesn't seem this script specific issue. Thanks for your help.

**Comment by ahmadawais** [comment]
Glad I could help!
