### ISSUE TITLE
Apple Silicone M1 error with Node Sass

### ISSUE THREAD

**Issue by Sam-Xronn** [ahmadawais/WPGulp#201]
Looks like Node Sass doesn't compile with WPGulp, even when running the terminal under rosetta d oyou have any steps to resolve this issue? Or is it a case of just waiting for third parties to update?

![Screenshot 2021-02-20 at 12 46 59](https://user-images.githubusercontent.com/21875066/108595864-e11ddd80-7379-11eb-944d-381f81621071.png)

**Comment by Sam-Xronn** [comment]
Resolved - 

For anyone else on the Google train after getting a new mac with the M1 chip. 

- Set you're terminal to rosetta mode
- Restart your terminal 
- Clear your local project from any legacy gulp/npm files
- Download the new files or in WP Gulp case using `npx wpgulp`

**Comment by jeffceriello** [comment]
Hi, I have tried that and it now works but have you found that wpgulp now compiles reeeeally slow on the M1 silicon? If yes, do you have any idea why that would be happening?
