### ISSUE TITLE
Watch task too slow on init

### ISSUE THREAD

**Issue by diegorochawebdg** [ahmadawais/WPGulp#22]
Your gulpfile is awesome! Everything is running ok, but always when I run the task default, the watch task spend so much time to start (30s +- ).
There's some trick what can I do to speed up the watch task? 
(Sorry about my poor english)

**Comment by ahmadawais** [comment]
The watch task depends on what kind of OS and computer you are using. The specs of your computer play a vital role here. 

I am sure you'll find the discussion here, in #20 quite effective in solving your issue.

**Comment by commwork** [comment]
On my MacOS MBP it needs 2 seconds, on my windows 10 machine (which is normally faster) it needs 30 seconds. But it's no big deal for me.

**Comment by ahmadawais** [comment]
You know how to customize it 👍 This is just a boilerplate :)
