### ISSUE TITLE
Use Clean CSS instead of UglifyCSS to keep first comment in style.min.css

### ISSUE THREAD

**Issue by kevinmamaqi** [ahmadawais/WPGulp#23]
Hello,

I've checked the uflifycss npm package and I can't find an option like keepspecialcomments in order to keep the theme info at the top in style.min.css, maybe using CleanCSS (https://www.npmjs.com/package/clean-css) would be an alternative.

I'm asking because maybe there are more reasons to use UglifyCSS instead of CleanCSS that I don't know.

**Comment by ahmadawais** [comment]
@kevinmamaqi to keep special comments just use `!`.

E.g. ```/*!```

**Comment by ahmadawais** [comment]
@kevinmamaqi Clean CSS looks pretty good, I will see if we can port to it. Your PR is welcomed if you want to do that. I am also working on a major release of WPGulp in the first quarter of 2017. We will have a lot more automation and a WPGulp CLI.
