### ISSUE TITLE
Vendor files ordering

### ISSUE THREAD

**Issue by allaire** [ahmadawais/WPGulp#25]
Hi @ahmadawais ,

First thanks for this project!

Let say I want to control the order of how the vendors are loaded, is there a better way then prefixing the file I need to load first with something like `0_` ?

Bootstrap 4 relies on tether.js, so I need to load it first :)

**Comment by allaire** [comment]
Found it:

```
var jsVendorSRC             = [
                                './assets/javascripts/vendor/tether.min.js', // Needed before bootstrap
                                './assets/javascripts/vendor/*.js'
                              ]; // Path to JS vendor folder.
```

**Comment by CatinhoCR** [comment]
> Found it:
> 
> ```
> var jsVendorSRC             = [
>                                 './assets/javascripts/vendor/tether.min.js', // Needed before bootstrap
>                                 './assets/javascripts/vendor/*.js'
>                               ]; // Path to JS vendor folder.
> ```

Are you doing this in the wpgulp.config file?

**Comment by julie-impuls** [comment]
How should you do this with the latest version of WPGulp?

**Comment by jeffceriello** [comment]
I am also struggling with this. Any solutions?
