### ISSUE TITLE
[SOLVED] Unable to compile Sass subdirectories

### ISSUE THREAD

**Issue by AndreaBarghigiani** [ahmadawais/WPGulp#27]
Hi Ahmad,
congrats for your hard work with this repo, I was looking to find a solution to implement BrowserSync and Gulp in my WordPress Theme Development workflow.

Thanks to your repo now I am able to solve that!

Anyway I have a little problem, I've created a `partials/` folder in my `scss/` folder (I've renamed from your `css/` to fit my needs) and I noticed that I am unable to let compile the imported partials when I modify them.

The only thing that I am able to do is run Gulp when I edit the `style.scss` file. This makes my work a little more complicated since to have the compiled CSS and to reload the browser I still have to update the `style.scss` file...

I've tried to modify the Gulpfile.js but seems that everything is ok because on the watchers there is the following code:
```
var styleWatchFiles         = './scss/**/*.scss';
gulp.task( 'default', ['styles', 'vendorsJs', 'customJS', 'images', 'browser-sync'], function () {
  gulp.watch( styleWatchFiles, [ 'styles' ] ); // Reload on SCSS file changes.
 });
``` 

I've edited your code to not mess this issue but from my point of view everything is fine. The styleWatchFiles is set properly but the watcher does not work...

Can you help me up with it?

**Comment by AndreaBarghigiani** [comment]
I've solved changing the path for `styleWatchFiles` from `./scss/**/*.scss` to `./scss/**/*`.

Don't know why this make any difference (because in that folder there are only `.scss` files but now it works ;)

Again congrats for your work, really impressed!

**Comment by ahmadawais** [comment]
@AndreaBarghigiani Glad, you were able to work out a solution. `BrowserSync` has a history of weird problems but it is the least bad solution for doing what it does.

>Again congrats for your work, really impressed!

That's very kind of you to say! 💯

BTW. I have something interesting coming up for WPGulp pretty soon. If you'd like to be notified, subscribe to my WordPress newsletter called Takeaway http://AhmadAwais.com/subscribe/
