### ISSUE TITLE
Gulp 4 Rewrite

### ISSUE THREAD

**Issue by JeremyEnglert** [ahmadawais/WPGulp#30]
Hi @ahmadawais, awesome project!

With Gulp 4 coming soon, is there any thoughts to incorporating those features into WPGulp? I'd love to get started on it, but don't want to duplicate work that already may be being worked on (I saw another note that you're working a a pretty large overhaul).

Let me know!

**Comment by ahmadawais** [comment]
Hey, @JeremyEnglert 
Yes, I have been looking into the series and parallel excutions feature, currently working on more automation to make it easy for users of WPGulp to customize the project. I think I will add them in the next major release. 

To keep yourself up to date with WPGulp you can signup for the updates here → http://eepurl.com/cLwjeH

**Comment by klihelp** [comment]
@JeremyEnglert as I assume you update on your project which reflects this github update/issue will be marked/closed followed by a helpful notification. Gulp 4 already out.


>> To keep yourself up to date with WPGulp you can signup for the updates here ...
