### ISSUE TITLE
Yeoman generator package - Enhancement

### ISSUE THREAD

**Issue by robmim** [ahmadawais/WPGulp#32]
Juste wanted to share the idea of implementing a yeoman generator project pack for WPGulp. Could be created with an empty http://underscores.me/ project or using Bedrock and/or Sage from Roots.io ???

PROS:
- Faster environment setup for development.
- Configurable options (theme and gulpfile.js) directly from yeoman generator.

**Comment by ahmadawais** [comment]
@robmim I had that and a few more things in my mind for a next major version. All of that will need a lot more time than I can set apart for at the moment. Feel free to jump right in. Contributors are most welcomed. I am already spending 50% of my time in Open Source and free software!

**Comment by ahmadawais** [comment]
Closing it for now, feel free to send in a PR.
