### ISSUE TITLE
Setting up Google Chrome workspace & sourcemaps?

### ISSUE THREAD

**Issue by runnickrun** [ahmadawais/WPGulp#41]
Hi, 
for some reason I can't make sourcemaps to work with Chrome workspaces. 

I've tried with style.min.css but obviously it didn't work, then I've tried with regular style.css but I still don't see SASS partials, only the style.css file. What should you map to what in workspace? 

Hopefully it makes sense.

**Comment by ahmadawais** [comment]
This was an issue and was fixed in the latest PR. Kindly, test it and report back.
