### ISSUE TITLE
browersync doens't load

### ISSUE THREAD

**Issue by astrocycles** [ahmadawais/WPGulp#42]
great work ! 

Maybe I missed something in the tutorial, but browsersync open a new window :  http://localhost:3000 and then loads forever. Any idea ? 

thanks

**Comment by shawnquinn** [comment]
Hey @astrocycles 

When you run `$ gulp browser-sync` or `$ gulp` (by default), then browsersync will auto open a new window if your options are set to `open: true`.

To prevent it from auto opening a new window every time, just change `open: true` to `open: false`. You can find the browsersync options in your `gulpfile.js` 

See below:

```
gulp.task( 'browser-sync', function() {
  browserSync.init( {
    proxy: projectURL,
    open: true,
    injectChanges: true,
    port: 8888
  } );
});
```

**Comment by ahmadawais** [comment]
@astrocycles That's the default behavior. Did you read the up to date tutorial [here](https://github.com/ahmadawais/WPGulp). 

@shawnquinn Thanks for the help with managing this FOSS project. I really can use all the help at the moment :)

**Comment by astrocycles** [comment]
Hi,
Thanks for your reply. For development I need the browersync refresh.
I tried on both repos : WP gulp and this nice WP starter theme [https://github.com/ahmadawais/WPGulpTheme](url)

Please check this video to see browersync behaviour.
[https://youtu.be/HxzaACtRZAM](url)

Many thanks

**Comment by ahmadawais** [comment]
WPGulp, this project is the only project that's up to date. So, you'll have to try it out. I can't be sure of your personal setup — but if you clean install it, this works perfectly!

**Comment by astrocycles** [comment]
Hi,
I re-installed everything and used the WPgulp repo. Sorry It doesn't work for me.

**Comment by marianrick** [comment]
@astrocycles I have got the same problem using AMPPS after a clean install using WPGulp. Are you using AMPPS for your local development server as well?

**Comment by ahmadawais** [comment]
@astrocycles @marianrick 
That looks like your local server problem. 

Have you guys set up the [`projectURL`](https://github.com/ahmadawais/WPGulp/blob/master/gulpfile.js#L33) — coz that's what BrowserSync is trying to connect to.

**Comment by marianrick** [comment]
@ahmadawais Yes, I have set it to something like `localhost:8888` as well as `fancydomains.dev` or similar ones.

To be honest I am confused about the setup of browser-sync. Wordpress needs a php and mysql server running, right? If so, do I have to run my local server with a working website (using AMPPS/MAMP/whatever) and afterwards run `$ gulp browser-sync` inside my themes root folder? Or do I only have to do the last step without a local setup? 

I have tried each of these while none of them works. While I can imagine, that its a local server problem, I am not completely sure about it. I have tried using browser-syncs `logLevel: "debug"`, but I do not see any helpful information in it (attached below).

While the browser-sync proxy is not able to load, each file change is detected and although fires the right tasks.

Is there some kind of best practice or possible way to narrow down this mistake (or even log this error within the gulp configuration)? I can imagine that a AMPPS setup for local Wordpress development is quite popular.

```17:42:18] Starting 'browser-sync'...
[BS] [debug] -> Starting Step: Finding an empty port
[17:42:18] Finished 'browser-sync' after 15 ms
[BS] [debug] Found a free port: 3000
[BS] [debug] Setting Option: port - 3000
[BS] [debug] +  Step Complete: Finding an empty port
[BS] [debug] -> Starting Step: Getting an extra port for Proxy
[BS] [debug] +  Step Complete: Getting an extra port for Proxy
[BS] [debug] -> Starting Step: Checking online status
[BS] [debug] Resolved www.google.com, setting online: true
[BS] [debug] Setting Option: online - true
[BS] [debug] +  Step Complete: Checking online status
[BS] [debug] -> Starting Step: Resolve user plugins from options
[BS] [debug] +  Step Complete: Resolve user plugins from options
[BS] [debug] -> Starting Step: Set Urls and other options that rely on port/online status
[BS] [debug] Setting multiple Options
[BS] [debug] +  Step Complete: Set Urls and other options that rely on port/online status
[BS] [debug] -> Starting Step: Setting Internal Events
[BS] [debug] +  Step Complete: Setting Internal Events
[BS] [debug] -> Starting Step: Setting file watchers
[BS] [debug] +  Step Complete: Setting file watchers
[BS] [debug] -> Starting Step: Merging middlewares from core + plugins
[BS] [debug] Setting Option: middleware - List []
[BS] [debug] +  Step Complete: Merging middlewares from core + plugins
[BS] [debug] -> Starting Step: Starting the Server
[BS] [debug] Proxy running, proxing: http://localhost:8888
[BS] [debug] Running mode: PROXY
[BS] [debug] +  Step Complete: Starting the Server
[BS] [debug] -> Starting Step: Starting the HTTPS Tunnel
[BS] [debug] +  Step Complete: Starting the HTTPS Tunnel
[BS] [debug] -> Starting Step: Starting the web-socket server
[BS] [debug] Setting Option: clientEvents - List [ "scroll", "scroll:element", "input:text", "input:toggles", "form:submit", "form:reset", "click" ]
[BS] [debug] +  Step Complete: Starting the web-socket server
[BS] [debug] -> Starting Step: Starting the UI
[BS] [debug] Setting Option: session - 1502206938583
[BS] [UI] Starting Step: Setting default plugins
[BS] [UI] Step Complete: Setting default plugins
[BS] [UI] Starting Step: Finding a free port
[BS] [UI] Step Complete: Finding a free port
[BS] [UI] Starting Step: Setting options also relevant to UI from BS
[BS] [UI] Step Complete: Setting options also relevant to UI from BS
[BS] [UI] Starting Step: Setting available URLS for UI
[BS] [debug] Getting option via path: urls
[BS] [UI] Step Complete: Setting available URLS for UI
[BS] [UI] Starting Step: Starting the Control Panel Server
[BS] [UI] Using port 3001
[BS] [UI] Step Complete: Starting the Control Panel Server
[BS] [UI] Starting Step: Add element events
[BS] [UI] Step Complete: Add element events
[BS] [UI] Starting Step: Registering default plugins
[BS] [debug] Getting option via path: urls,external
[BS] [UI] Step Complete: Registering default plugins
[BS] [UI] Starting Step: Add options setting event
[BS] [UI] Step Complete: Add options setting event
[BS] [debug] +  Step Complete: Starting the UI
[BS] [debug] -> Starting Step: Merge UI settings
[BS] [debug] Setting Option: urls - Map { "local": "http://localhost:3000", "external": "http://192.168.178.161:3000", "ui": "http://localhost:3001", "ui-external": "http://192.168.178.161:3001" }
[BS] [debug] +  Step Complete: Merge UI settings
[BS] [debug] -> Starting Step: Init user plugins
[BS] [debug] Setting Option: userPlugins -
[BS] [debug] +  Step Complete: Init user plugins
[Browsersync] Proxying: http://localhost:8888
[Browsersync] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.178.161:3000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.178.161:3001
 ----------------------------------------```

**Comment by ahmadawais** [comment]
>To be honest I am confused about the setup of browser-sync. Wordpress needs a php and mysql server running, right? If so, do I have to run my local server with a working website (using AMPPS/MAMP/whatever) and afterwards run $ gulp browser-sync inside my themes root folder? Or do I only have to do the last step without a local setup?

Obviously, your server should be running. The browsersync part in WPGulp is only proxying it over your pre-running server that you need to run before you run WPGulp. 

There you go. If your site is running at `localhost:8888` then `gulp` down there and it should work!

**Comment by ahmadawais** [comment]
I'd recommend DesktopServer https://serverpress.com/get-desktopserver/

**Comment by marianrick** [comment]
Ah, thanks a lot @ahmadawais. So the `projectUrl` has to be the same, as the already running Wordpress page. I thought browser-sync creates kind of its own server. Thanks for your suggestions and support! Although thanks for the serverpress.com suggestion.

**Comment by ahmadawais** [comment]
@marianrick Anytime!
Browser sync can setup a server on its own, but it is mostly for the frontend stuff. Since WP is PHP based, BS allows for a proxy URL which is the project URL here. So, you need your site running before starting WPGulp.

> Thanks for your suggestions and support! 

Sure, thing! If you feel like that WPGulp helps you then you can [support](https://pay.paddle.com/checkout/515568) the project :)

Cheers!

**Comment by astrocycles** [comment]
@marianrick   @ahmadawais 
Hi,
Unfortunately I never managed to make this repo work for myself. 
So what I did is used this one https://github.com/zellwk/gulp-starter-csstricks which is a starter kit added bootstrap in it with the nmp command.

This makes a nice dev environment without WP. Browsersync loads super fast . Then when you are happy with the html site, you can move your code to WP in sage or mamp.
here is a nice tutorial found here https://www.youtube.com/watch?v=ZfTBNvDwIpk
Hope it helps 

_What I'd like to achieve is to bring this repo to a next level, namely  adding a few gulp dependencies to pass the 100% google pagespeed._

**Comment by ahmadawais** [comment]
@astrocycles I'd appreciate if you'd not link to other gulp repos here, it will only confuse the users!

I have described the situation, above. You have to start your server before starting WPGulp. Did you do that?

**Comment by astrocycles** [comment]
Yes I did. 
Sorry If offended you, however  you withdrew my post It could have helped some people. 
The goal is to make it work, I guess.

**Comment by ahmadawais** [comment]
>Yes I did.

Did that work? If not, did you try with DesktopServer?

>Sorry If offended you, however you withdrew my post It could have helped some people.

None was taken. I did that to not confuse people.

>The goal is to make it work, I guess.

It works, pretty sure the issue is at your end.

**Comment by astrocycles** [comment]
Hi,
I tried on Mamp and xamp with bitnami. The result is even worse on Mamp because it makes browsersync open the htdocs folder instead of opening the index.

I'm not sure what's wrong, but I can tell you that another Gulp repo is working. It loads the index file without any side server.

**Comment by ahmadawais** [comment]
@astrocycles WPGulp is not a server! It proxies over your already running server. If it is openning htdocs then you have WPGulp placed in the wrong dir. It should placed in the root folder of the theme or plugin you are working in.

**Comment by astrocycles** [comment]
Yes of course it is installed in the wp-content/theme/my-theme

The real issue is because you suggest to `sudo npm install`.
I had to re-install all my setup.

here is the solution https://gist.github.com/rcugut/c7abd2a425bb65da3c61d8341cd4b02d#never-run-npm-as-sudo-so-never-do-sudo-npm-install-
