### ISSUE TITLE
Duplicate output CSS file.

### ISSUE THREAD

**Issue by khoipro** [ahmadawais/WPGulp#47]
I want to create these structures in my WP theme:

```
/src/
-- /scss/
---- /main.scss
----/base/
------/typography.scss
----/modules/
----/partials/
-- /js/
----/vendor/
----/lib/
----/modules/
```

And tried to modify gulpfile.js as below:

```
// Style related.
var styleSRC                = './src/scss/*.scss'; // Path to main .scss file.
var styleDestination        = './assets/css/'; // Path to place the compiled CSS file.
// Default set to root folder.
```

However when output, it loads to assets/css/assets/css/main.min.css

Can you please check that kind of issue?

**Comment by theenoahmason** [comment]
Can confirm. Makes using this package impossible. Will check back later for a fix. So promising :(

**Comment by theenoahmason** [comment]
@khoipro This is happening because the sourcemap location is too specific, it should be relative if you are in the pipe already.

Make sure the line that writes the sourcemap is the following: `.pipe( sourcemaps.write ( './' ) )` This makes sure that the sourcemaps get written alongside the min files, reguardless of where the source css is. This should never change.

**Comment by theenoahmason** [comment]
@ahmadawais I just experienced this issue and solved with the above ^. Your latest release in the tags section of this repo is not working with even small customization, and a lot of deps are out of date, yet aren't being mentioned in `npm outdated` for some reason.

**Comment by ahmadawais** [comment]
@theenoahmason We are close to releasing a major upgrade. Can you help test it to see if things are looking good there? It's there in [the v2.0.0 branch](https://github.com/ahmadawais/WPGulp/tree/v2.0.0).

**Comment by ahmadawais** [comment]
Also you should try the gulpfile in the master with the installation instructions, that is already updated.

**Comment by theenoahmason** [comment]
@ahmadawais gotcha, sorry for confusion! maybe release 1.0.4 with just that fix for people who may still be using 1.0?

**Comment by ahmadawais** [comment]
Sure thing!

**Comment by ahmadawais** [comment]
Can you check this and repoen for the latest v2 release?
