### ISSUE TITLE
Not updating SCSS after default event

### ISSUE THREAD

**Issue by codeThaGlobe** [ahmadawais/WPGulp#49]
**This is a great resource! Thank you for the clean and documented code!!!**

I have done the config and got it running. It builds fine when I run the default task, but does not rebuild or inject my styles when I save the .scss after that. No error, but no notification of task completion either.

<img width="831" alt="screen shot 2017-09-05 at 5 23 46 pm" src="https://user-images.githubusercontent.com/5844599/30089065-3767293a-925f-11e7-92d3-6367df15a79d.png">

Any thoughts?

**Comment by codeThaGlobe** [comment]
Of course as soon as I posted my issue I figured it out 🥇 

`styleWatchFiles` has its own var

**Comment by ahmadawais** [comment]
@codeThaGlobe Glad to know that. 

P.S. Feel free to subscribe to my newsletter called WPTakeaway https://WPTakeaway.club/
