### ISSUE TITLE
Issue with reload

### ISSUE THREAD

**Issue by akmur** [ahmadawais/WPGulp#5]
Hei there, I'm having the following issue:

when I change a style, the change gets injected but also triggers a browser refresh.

Did you manage to get CSS injection working?

Cheers!

**Comment by ahmadawais** [comment]
@akmur That is not an issue with WPGulp, you need to create one with BrowserSync. Sometimes, it injects CSS and sometimes it refreshes the page. 

By default WPGulp is set to refresh and you need to set inject CSS true on this line https://github.com/ahmadawais/WPGulp/blob/master/gulpfile.js#L134

I hope you are doing that.

**Comment by akmur** [comment]
Thanks for your answer, yes I'm doing that but browser sync doesn't want to behave :)

**Comment by ahmadawais** [comment]
Yup :)

**Comment by ahmadawais** [comment]
Hey, I just committed an update and commented the media queries merge lines. These two lines were causing CSS to not reload 

```
// Uncommenting these two lines will help merging the media queries
// but there is a known issue, SCSS changes stop reloading the browser
// which is why for now I recommend you to only uncomment these two lines
// to process the media queries.
//.pipe(filter('**/*.css')) // Filtering stream to only css files
//.pipe(mmq({ log: true })) // Merge Media Queries only for .min.css version.
```

**Comment by akmur** [comment]
Hello, I managed to get it working in the end, here is how I am doing it if you are interested, basically I am streaming into browsersync like you do, and my serve task is just doing that, serving. My reload issue was caused by watching sass maps.

https://github.com/akmur/WPGulp/blob/master/gulpfile.js

Thanks for your help

**Comment by ahmadawais** [comment]
So, @akmur 
This line solves the problem? 
https://github.com/akmur/WPGulp/blob/master/gulpfile.js#L158

**Comment by akmur** [comment]
Yes, that line solves the problem, I just have to start the server, then
the changes get streamed into BrowserSync.

One thing worth mentioning is to make sure that your watchers are not
watching for sass maps changes by mistake, as they would also trigger a
browser refresh right after style injection

On Sat, 19 Mar 2016 at 08:02 Ahmad Awais <notifications@github.com> wrote:

> So, @akmur <https://github.com/akmur>
> This line solves the problem?
> https://github.com/akmur/WPGulp/blob/master/gulpfile.js#L158
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ahmadawais/WPGulp/issues/5#issuecomment-198649452>
>
-- 
Alessandro Muraro
@akmur
alexmuraro.me

**Comment by ahmadawais** [comment]
@akmur I got the idea and worked around a little. There were multiple instances where we could use the stream reloading. 

Just pushed an update. Merge Media Queries, Line Endings and Inject CSS working fine now.
