### ISSUE TITLE
Translation folder path

### ISSUE THREAD

**Issue by Tolomeo** [ahmadawais/WPGulp#50]
Just to notify that 'translate' gulp task compiles the .pot file into the wrong folder because

```
gulp.dest(destFile)
```

should be

```
gulp.dest(translatePath)
```

Thanks for the great job you've done

**Comment by ahmadawais** [comment]
Thanks. I will look into that. I think the Pot plugin just got changed.

**Comment by ahmadawais** [comment]
@Tolomeo Can you check if this PR is what you're talking about? #45 

Review it for me? I am on mobile at the moment.

**Comment by Tolomeo** [comment]
Yes, that's what I mean 👍

**Comment by ahmadawais** [comment]
I just merged it :)
