### ISSUE TITLE
Support for ES6

### ISSUE THREAD

**Issue by davision** [ahmadawais/WPGulp#53]
First of all, thank you for your amazing job! Everything just works out of the box with amazing performance. One thing I was considering having maybe is support for EcmaScript 6. Did you have this support in mind? Minifier now breaks, if you use new JS features and syntax.

**Comment by ahmadawais** [comment]
Obviously, there is not support for ES6 in WPGulp right now, but that's what's coming in the next update before the end of this year hopefully. Unless you want to send a PR.

**Comment by davision** [comment]
Great! Will try to do my best.

**Comment by phra** [comment]
@davision @ahmadawais have a look at this [PR](https://github.com/ahmadawais/WPGulp/pull/54).

**Comment by davision** [comment]
Now that was sweet! Thanks @phra!

**Comment by ahmadawais** [comment]
@phra Thanks. I will look into it. I am also releasing basic ES6 support for WPGulp in a few hours :)

**Comment by ahmadawais** [comment]
@davision Can you also mention the test case where ES6 breaks so that I can test it against the PR and what I am releasing?

**Comment by davision** [comment]
Actually, your current setup breaks whenever you use an ES6 specific syntax, for example "let" declaration.

**Comment by phra** [comment]
@davision @ahmadawais  can't you just check out if it's working with my patch?

**Comment by davision** [comment]
Well, it works! I thought I was clear on that with my first reply :)

**Comment by dingo-d** [comment]
All you need to do is to add `babel` to `package.json` and rename `gulpfile.js` to `gulpfile.babel.js`, and you can use ES6 in it :)

**Comment by ahmadawais** [comment]
@dingo-d Seriously? I was looking into using the gulp-babel package. 

Have you tested all the other packages? Do they work? PR's welcomed.

**Comment by dingo-d** [comment]
I've done a mix of gulp and webpack on an os project I'm working on for the company I work for: https://github.com/infinum/json-wp-post-parser. Feel free to check it out.

If I'll manage some time I'll fork and try to rewrite it in ES6. I have one plugin that I need to put on wp.org so that's a priority atm :D

**Comment by JeremyEnglert** [comment]
Just a heads up for everyone interested, a PR has been submitted for WP Gulp 2.0 to add ESNext support with Babel!

https://github.com/ahmadawais/WPGulp/pull/80

**Comment by ahmadawais** [comment]
Fixed in #80
