### ISSUE TITLE
Newly added files not detected by browser-sync watch task

### ISSUE THREAD

**Issue by marianrick** [ahmadawais/WPGulp#58]
A few times I thought browser-sync was broken or not configured the correct way, as newly added files will not be recognized in the watch folders. 

For example I add `_global.scss` as file, import it in `/scss/style.scss`:

- when I click save inside `style.scss`, the import runs and everything seems to be fine
- when I click save inside `_global.scss` nothing happens

After stopping and running the `gulp` task again, saving the new `_global.scss` file although does cause a hot reload.

Is there a way to detect newly added files inside gulp and register them? I did not found anything about this in the web to add some input on my own.

**Comment by ahmadawais** [comment]
Same here. You have to stop and run again as the main sass file is being used here and it needs to be reloaded, I have not get enough time to look into that for now, but if you want to make WPGulp better on this front, I'll def welcome your PR.

**Comment by marianrick** [comment]
I have tried to write it on my own, but this was not working 100% and seemed to be rather hacky. Maybe there is some other person able to implement it in a more professional way in here? 

The solution seemed to be to use `browserSync.watch()` instead of `gulp.watch()`, based on [this stack answer](https://stackoverflow.com/a/32988499/2113599)

**Comment by JeremyEnglert** [comment]
This no longer appears to be an issue in 2.0, but I'm not 100% sure why.

**Comment by marianrick** [comment]
But it’s great nevertheless

**Comment by JeremyEnglert** [comment]
@marianrick - can you confirm the 2.0 branch works as expected?

**Comment by marianrick** [comment]
Currently it behaves as expected in my test cases, so I would say yes, it works great.

**Comment by ahmadawais** [comment]
That's great. Closing this issue then.
