### ISSUE TITLE
Server running

### ISSUE THREAD

**Issue by bdadev** [ahmadawais/WPGulp#60]
Sorry for the question but do I need to have MAMP running?

I'm trying to run my project but to no avail.

Thank you!

**Comment by dmhendricks** [comment]
You do not have to have a web server/MAMP running to use WPGulp.

What is happening and/or what sort of errors are you getting? What operating system are you running it on?

**Comment by bdadev** [comment]
It does not display error messages in the console or in git bash, including the messages of the tasks that were executes are displayed in the browser that by the way I found sensational.

But I stayed until 2:00 AM analyzing until I decided to configure the port of the browser sync for 8080 running the MAMP server, just so I was able to run and gave everything cetto friend.

Until then I used the yeoman because my sites were static, however I learned to use wordpress and I missed the optimization for the front end when I discovered its creation.

Thank you so much for everything.

**Comment by ahmadawais** [comment]
Oh glad you figured it out. Yes, WPGulp needs your WordPress server to be running. I'd recommend you to try DesktopServer for that.

**Comment by bdadev** [comment]
Thanks for support @ahmadawais. WPGulp is incredibly effective. You do a great job.

**Comment by ahmadawais** [comment]
@bdadev That's very kind of you to say! 💯

Join us at #61 → 🚀  WPGulp 2.0 Goals + Call for Contributors!
