### ISSUE TITLE
Incremental Builds and Caching + Gulp 4.0

### ISSUE THREAD

**Issue by JeremyEnglert** [ahmadawais/WPGulp#63]
- [x] Update to Gulp 4.0
- [x] Rebuild tasks to take advantage of caching.

This checklist will be updated as new or more detailed tasks become apparent.

**Comment by JeremyEnglert** [comment]
@ahmadawais - came across something a bit interesting. As is, the JS tasks don't have anything to cache.

Check it out here: https://gist.github.com/JeremyEnglert/cfbbc14a69ef5a38d78634230a97d88e

**Comment by ahmadawais** [comment]
@JeremyEnglert I didn't get that. Also take a look at the latest commit where I added caching for images and live reloading for images. Maybe try and use the same caching module?

**Comment by JeremyEnglert** [comment]
Since I see we're adding linting, that can be part of what is cached on the JS tasks.

For the image task, we don't need an external module for that. As we don't have to return the images to the stream, `gulp.lastRun` should be sufficient.

**Comment by JeremyEnglert** [comment]
In regards to `gulp-cache` vs. `gulp-cached`, they seem similar. `gulp-cached` seems to have an easier to understand process (in my opinion) and is slightly more popular. However, I'm open to changing if you heavily favor `gulp-cache`.

**Comment by ahmadawais** [comment]
@JeremyEnglert Sure if lastRun is enough in the JS task then let's go with that.

About the image task, I did prefer `gulp-cached` for the same reason, but it was some how buggy for what we needed it to do. E.g. right now the images are watched, any new image placed in the set folder will get processed, and that's being done only once. Even if you change the name of that image. 

`gulp-cached` just didn't work for some reason.

**Comment by JeremyEnglert** [comment]
I meant gulp.lastRun should be enough for the images task. But I'll need to confirm.

**Comment by ahmadawais** [comment]
I don't think so. It's not just lastRun, it's more than that when it comes to caching.

**Comment by JeremyEnglert** [comment]
I just noticed the images task isn't part of the watch task.

What exactly are you trying to cache with images? Are we just trying to make sure the same images are not optimized more than once?

**Comment by JeremyEnglert** [comment]
Great article on incremental builds and caching: https://fettblog.eu/gulp-4-incremental-builds/

**Comment by JeremyEnglert** [comment]
So `gulp.lastRun` doesn't work with a Sass build the way we'd hope. It appears that `gulp.lastRun` only watches the timestamp on `css/styles.scss`, which doesn't change when a `_.scss` file is changed. 

I tried changing `styleSRC` to  `./assets/css/*.scss`, but still didn't have any luck. 

When Googling, I wasn't able to find much about caching Sass builds - everything seems to be about JS.

**Comment by ahmadawais** [comment]
I think node-sass itself has a cache.

**Comment by JeremyEnglert** [comment]
In that case, I think we can consider this task done.

- JS tasks are cached via gulp.LastRun and gulp-remember
- Image task is cached by gulp-cache
- Style task is cached by node-sass
