### ISSUE TITLE
☕️ Create Separate Config File

### ISSUE THREAD

**Issue by JeremyEnglert** [ahmadawais/WPGulp#65]
This is for the 2.0 branch. I'll knock this out ASAP as it will most likely effect other changes to the project. 

- [x] PR #66 
- [x] Formatting

**Comment by ahmadawais** [comment]
How are we going to use that? We can use a pre-built parser from Awesome Node list.

**Comment by JeremyEnglert** [comment]
I don't think we need to do anything fancy. Other large projects simply move the config to a .js file and call that file at the top of the Gulpfile. I made a PR for this. 

https://github.com/ahmadawais/WPGulp/pull/66

**Comment by ahmadawais** [comment]
@JeremyEnglert JavaScript based config is definitely the right choice here. I have been reviewing your work and have requested second changes. I hope it helps you learn how it's done and make WPGulp better. I'd also like to add you as a collaborator on this project. You're definitely improving WPGulp and that's the best criteria of judgment here. Let me know :)

**Comment by JeremyEnglert** [comment]
I'm all for that! 

I'm also 100% up for a different method if you think export modules are not the right way to go.

**Comment by ahmadawais** [comment]
@JeremyEnglert Thanks for fixing this issue. I think we can safely close it for now. Also, check your email. I sent one a couple of days ago.
