### ISSUE TITLE
⚒ Better Error Handling for All the Tasks 

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/WPGulp#68]
WPGulp's error handling is trivial at best. I have had implemented different error handlers for my WordPress projects, I want to improve upon that part of WPGulp in the next version. 

- [x] Handle all errors without breaking the dev-workflow.
- [x] Improved error reporting.
- [ ] Maybe use chalk to make the console look better.

**Comment by JeremyEnglert** [comment]
This will work in tandem with the Gulp caching we are implementing. As we will only want to test recently changed files.

**Comment by ahmadawais** [comment]
@JeremyEnglert you are right about that. But we need the entire error handling module to be ready for each task. :)

**Comment by ahmadawais** [comment]
@JeremyEnglert Assign this task to yourself if you're up for it. I am thinking `plumber` would be a great addition. Used to have it back then but then removed it. Not sure if we need one but we do.

**Comment by JeremyEnglert** [comment]
> @JeremyEnglert Assign this task to yourself if you're up for it. I am thinking plumber would be a great addition. Used to have it back then but then removed it. Not sure if we need one but we do.

I think I need to be a contributor to assign the task to myself.

**Comment by ahmadawais** [comment]
@JeremyEnglert check your email I sent you the invite twice. Or just go here https://github.com/ahmadawais/WPGulp/invitations

**Comment by JeremyEnglert** [comment]
Oh, sweet! My apologies - my email is giving me hell this week.

**Comment by ahmadawais** [comment]
@JeremyEnglert any progress on this?

**Comment by JeremyEnglert** [comment]
Sorry, been a bit tied up with Foundation.

I can tackle this over the weekend.

**Comment by JeremyEnglert** [comment]
Done in https://github.com/ahmadawais/WPGulp/pull/89.

**Comment by ahmadawais** [comment]
Thanks for that, @JeremyEnglert ✅
