### ISSUE TITLE
images task not moving all optimised images to imagesDestination

### ISSUE THREAD

**Issue by mischacolley** [ahmadawais/WPGulp#7]
I've placed a bunch of images inside of `assets/img/raw` with the destination set to `assets/img/optimised`. Inside of raw there are some files inside of other directories. For some reason the task is completing but not all images are being copied into `assets/img/optimised`. Any ideas?

**Comment by ahmadawais** [comment]
I am unable to automate it, which is why I documented that it only runs once and later you can run it via `gulp image` command. Kindly read the docs in the `gulpfile.js`.

https://github.com/ahmadawais/WPGulp/blob/master/gulpfile.js#L250-L251

**Comment by mischacolley** [comment]
Thanks for the reply @ahmadawais. Yeah I had read your docs on running `gulp images` but still getting the same result with it not processing / moving all the raw images.

**Comment by ahmadawais** [comment]
@mischacolley  Can you be more elaborate? So, that I could recreate the issue at my end?
