### ISSUE TITLE
No sass sourcemap here either

### ISSUE THREAD

**Issue by djmtype** [ahmadawais/WPGulp#9]
@ahmadawais As you recommended I try this repo with WPGulpTheme. I assumed because the gulpfile was more recent. Although, sass sourcemaps are being generated, they are not showing up inside Chrome devtools. A minified stylesheet is only being displayed. [Screenshot](https://cloudup.com/cfxJNpcifa9)

**Comment by ahmadawais** [comment]
@djmtype Can you change the enqueued CSS with `style.css` instead of `style.min.css` And try again. Coz it works perfect at my end. Right now on mobile.

**Comment by ahmadawais** [comment]
Just uncomment this line https://github.com/ahmadawais/WPGulpTheme/blob/master/functions.php#L144 and comment the line below it.
