### ISSUE TITLE
How to include bower dependencies in vendor?

### ISSUE THREAD

**Issue by frontenddevguy** [ahmadawais/WPGulp#93]
I am trying to add a dependency but appears this is not set up by default?

I tried adding:

`var bower        = require('gulp-bower'); // bower dependencies`

and

```
 gulp.task('bower', function() {
  return bower({ directory: './js/vendor' })
 });
```
before the vendors task,
but nothing is being piped to vendors folder.
I changed my structure to gulp-dev folder outside the wp theme folder, which is otherwise working fine.

**Comment by cdils** [comment]
It looks like [WPGulp v2](https://github.com/ahmadawais/WPGulp/tree/v2.0.0) no longer includes Bower (Bower is deprecated). [Webpack](https://webpack.js.org/) is a popular alternative

**Comment by ahmadawais** [comment]
Bower is deprecated and no longer supported. You're right. 
I'd love for you to contribute webpack for that, but don't you think that'd be an overkill? I use Gulp where I don't use webpack. 

🤔Let me know how you see both potentially integrated?

**Comment by cdils** [comment]
@ahmadawais Agreed that webpack has a lot of overlap with Gulp. I've used Bower on previous projects but have actually decided (for simplicity's sake) just to use NPM to bring in the front-end dependencies I need.

**Comment by ahmadawais** [comment]
@frontenddevguy you'll have to pick a vendor file and place it in the vendors folder. If you want dependency management then webpack is the way to go. I am building something along that the lines for that as well.

**Comment by frontenddevguy** [comment]
@ahmadawais That's what I was attempting to do, and it works, but creates a recursive structure like plugin-a/plugin-a, and so the built vendors file includes code twice. That's what I was hoping for a pointer on by posting the above code.

It would be great to have a boilerplate for webpack with Wordpress definitely.
Not all of us are that technical and good with Js, but still want to use best practices, so I think it would help the community a lot :)

**Comment by cdils** [comment]
@frontenddevguy Just my two cents, but if you want to use Webpack, I'd ditch Gulp altogether. Here's an example of a "Gulp-free" [Webpack boilerplate for WordPress](https://github.com/danderozier/wordpress-webpack-boilerplate). (I have note used that code and can't comment on it other than to say what you're asking for exists). :)

**Comment by ahmadawais** [comment]
Closing this issue as it's pretty much addressed.

**Comment by jameelevans** [comment]
> @frontenddevguy Sure I understand that. Good news for you is that I am sitting on 95% completed WordPress and webpack Boilerplate for a couple of months. I want to make it into a dev-tool before I open source it. But I am planning to do that soon. @cdils Gulp and webpack do work together. Moreover, most of the webpack boilerplates for WordPress that I found were pretty stale.

Cant wait to see what you have in store

**Comment by ahmadawais** [comment]
Check out my WordSesh talk from 2018. https://WordSesh 2018.ahmadawais.com and you'll be able to set it up.
