### ISSUE TITLE
Sourcemap for the minified css?

### ISSUE THREAD

**Issue by rahulnever2far** [ahmadawais/WPGulp#95]
Is it possible to get sourcemap for the minified css? I tried adding `.pipe(sourcemaps.write('./'))` after `.pipe(minifycss()` but it doesn't generate the correct sourcemap :(

**Comment by ahmadawais** [comment]
What is your usecase here?

**Comment by ahmadawais** [comment]
Take a look at how v2 handles this and see if we still need this. Then reopen if required.
