### ISSUE TITLE
Remove / drastically eliminate comments

### ISSUE THREAD

**Issue by selrond** [ahmadawais/WPGulp#96]
Comments are widely considered [Code smell](https://en.wikipedia.org/wiki/Code_smell).

Aside from that, I've personally found them really annoying while working with WPGulp. 

In my view,

1. Gulp's API is reasonably self-documentative to not need any comments
2. Comments, in general, should tell **why** is the code here, not **what** it's doing; comments in WPGulp are basically the same thing `pipe()`s do, just rewritten in English 
3. Keeping comments in sync with the code, once one starts customising WPGulp tasks is a real pain in the ass

@ahmadawais what do you think?

**Comment by ahmadawais** [comment]
I think it's a dev tool and in dev tools, throughout the community, it's a general standard good practice to use more and more comments. The next major version of WPGulp will be hidden away in npm modules so you only will need to just use a file called wpgulp.js or something. 

I hope that will help.

**Comment by selrond** [comment]
@ahmadawais But the comments really don't make any sense here - they just repeat what `pipe()`s are doing.

**Comment by selrond** [comment]
Consider this: 

```js
/**
 * Task: `images`.
 *
 * Minifies PNG, JPEG, GIF and SVG images.
 *
 * This task does the following:
 *     1. Gets the source of images raw folder
 *     2. Minifies PNG, JPEG, GIF and SVG images
 *     3. Generates and saves the optimized images
 *
 * This task will run only once, if you want to run it
 * again, do it with the command `gulp images`.
 *
 * Read the following to change these options.
 * @link https://github.com/sindresorhus/gulp-imagemin
 */
gulp.task( 'images', function() {
	return gulp.src( config.imgSRC )
		.pipe(
			cache(
				imagemin([
					imagemin.gifsicle({ interlaced: true }),
					imagemin.jpegtran({ progressive: true }),
					imagemin.optipng({ optimizationLevel: 3 }), // 0-7 low-high.
					imagemin.svgo({
						plugins: [ { removeViewBox: true }, { cleanupIDs: false } ]
					})
				])
			)
		)
		.pipe( gulp.dest( config.imgDST ) )
		.pipe( notify({ message: 'TASK: "images" Completed! 💯', onLast: true }) );
});
```

How about replacing it with a one-line description about what the task is intended to do, and giving a link to a wiki / `README.md` section in the documentation?

**Comment by selrond** [comment]
Recommended reading: 

- [anti patterns - "Comments are a code smell" - Software Engineering Stack Exchange](https://softwareengineering.stackexchange.com/questions/1/comments-are-a-code-smell)
- [Code Tells You How, Comments Tell You Why](https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/)

**Comment by marianrick** [comment]
I think this highly depends on your level of skill. That may be wrong, but I think especially those “out of the box” scripts are used by a wide range of devs.

At the beginning these comments were pretty helpful for myself to understand what was going on. 

>I would hope, anyway, that any developers working on a given project were at least familiar enough with the development language to read what is written and understand what it is doing.

I think that’s the most important point: Who’s your target group? Is this a tool for beginners or for the lazy pros?

**Comment by selrond** [comment]
@marianrick I think it's really important to make a distinction between *comments* and *documentation*. They're **not** (or very rarely) the same thing. 

I'm not against either of the two, I'm all for proper and sensible usage of them.

Two solutions I see:

1. Move comments to documentation outside of `gulpfile.js`, only leave ones that explain **why** some obscure code is where it is; or
2. put some auto-generating documentation tool in place to use the comments present in `gulpfile.js`

**Comment by ahmadawais** [comment]
🤔 I agree with @marianrick and many many developers have said the same thing to me. It's also my personal belief that more comments in dev-tooling are better. It's helped me a lot. Many of the dev-tools out there agree with this stance. E.g. Create React App. 

So, I am going to close this ticket with the appreciation for discussion but not going to remove the comments. Thanks for chiming in. 👋
