### ISSUE TITLE
`package-lock.json` is not being ignored, nor present

### ISSUE THREAD

**Issue by selrond** [ahmadawais/WPGulp#97]
`package-lock.json` is created upon `npm install`, but it's not in this repository, nor present in `.gitignore` - what's the expected behavior here @ahmadawais?

**Comment by ahmadawais** [comment]
That's a file that keeps track of everything for your project via NPM. I think we should keep it that way. You can choose to use it or ignore it.

**Comment by selrond** [comment]
@ahmadawais I do know what it does, however, the very purpose of it is to ensure your dependencies stay exactly the same upon every installation - are you really confident about that?

[from the docs](https://docs.npmjs.com/files/package-lock.json):

> It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
>
> This file is intended to be committed into source repositories, and serves various purposes:
>
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> - Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> - To facilitate greater visibility of tree changes through readable source control diffs.
> - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

**Comment by lilolbear** [comment]
I have experienced the horrors of a mismatched package version creating strange errors.

**Comment by selrond** [comment]
Also, Gulp (and its' plugins) makes use of many, many dependencies by design, so this is a must as far as I'm concerned
